application: ceatquizzers
version: 2
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /javascripts
  static_dir: javascripts
  
- url: /images
  static_dir: images
  
- url: /questions/svg-edit
  static_dir: svg-edit
  
- url: /svg-edit
  static_dir: svg-edit

- url: /users/.*
  script: users/users.py
  login: admin
  
- url: /questions/.*
  script: questions.py
  
- url: /quizzer/.*
  script: quizzer.py

- url: .*
  script: main.py
